### ISSUE TITLE
Repeated build errors

### ISSUE THREAD

**Issue by gerrit** [robrix/Box#29]
Running into errors with building box (2.0 and 1.2.2) on my system (OS X 10.10.5) after installing Xcode 7.0. (but manually reverting to 6.4)

```
$ xcode-select -p
/Applications/Xcode 6.4.app/Contents/Developer

$ xcodebuild -version
Xcode 6.4
Build version 6E35b

$ cat Cartfile 
github "robrix/Box" "2.0"

$ carthage bootstrap

carthage bootstrap
*** Checking out Box at "2.0"
*** xcodebuild output can be found in /var/folders/jv/5fg0gqbd6gj861f82prqvw240000gp/T/carthage-xcodebuild.3SM7TP.log
*** Building scheme "Box-Mac" in Box.xcodeproj
** BUILD FAILED **


The following build commands failed:
    CompileSwift normal x86_64 <project-dir>/Carthage/Checkouts/Box/Box/Box.swift
    CompileSwift normal x86_64 <project-dir>/Carthage/Checkouts/Box/Box/MutableBox.swift
    CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(3 failures)
<project-dir>/Carthage/Checkouts/Box/Box/Box.swift:6:37: error: use of undeclared type 'CustomStringConvertible'
<project-dir>/Carthage/Checkouts/Box/Box/Box.swift:31:17: error: missing argument label 'stringInterpolationSegment:' in call
<project-dir>/Carthage/Checkouts/Box/Box/MutableBox.swift:8:51: error: use of undeclared type 'CustomStringConvertible'
<project-dir>/Carthage/Checkouts/Box/Box/MutableBox.swift:25:17: error: missing argument label 'stringInterpolationSegment:' in call
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
    CompileSwift normal x86_64 <project-dir>/Carthage/Checkouts/Box/Box/Box.swift
    CompileSwift normal x86_64 <project-dir>/Carthage/Checkouts/Box/Box/MutableBox.swift
    CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(3 failures)

$ cat /var/folders/jv/5fg0gqbd6gj861f82prqvw240000gp/T/carthage-xcodebuild.3SM7TP.log
<project-dir>/Carthage/Checkouts/Box/Box/Box.swift:6:37: error: use of undeclared type 'CustomStringConvertible'
public final class Box<T>: BoxType, CustomStringConvertible {
                                    ^~~~~~~~~~~~~~~~~~~~~~~
<project-dir>/Carthage/Checkouts/Box/Box/Box.swift:31:17: error: missing argument label 'stringInterpolationSegment:' in call
                return String(value)
                              ^
                              stringInterpolationSegment: 

[snip]

<project-dir>/Carthage/Checkouts/Box/Box/MutableBox.swift:8:51: error: use of undeclared type 'CustomStringConvertible'
public final class MutableBox<T>: MutableBoxType, CustomStringConvertible {
                                                  ^~~~~~~~~~~~~~~~~~~~~~~
<project-dir>/Carthage/Checkouts/Box/Box/MutableBox.swift:25:17: error: missing argument label 'stringInterpolationSegment:' in call
                return String(value)
                              ^
                              stringInterpolationSegment: 
```

**Comment by robrix** [comment]
Box 2.0 requires Swift 2 and ergo Xcode 7+. 1.2.2 should build fine with 6.4.
